name: Deploy Infrastructure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Initialize Terraform
        working-directory: terraform/infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform init -reconfigure

      - name: Plan Resources
        working-directory: terraform/infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform plan -out=tfplan

      - name: Apply Resources
        working-directory: terraform/infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform apply -auto-approve tfplan


      - name: Check for Changes in CSV Files
        id: check_csv_changes
        run: |
              git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE "files/SF_HOMELESS_ANXIETY.csv|files/SF_HOMELESS_DEMOGRAPHICS.csv" && echo "changed=true" || echo "changed=false" >> $GITHUB_ENV

      - name: Upload Updated CSV Files to S3
        if: env.changed == 'true'
        run: |
              aws s3 cp ./files/SF_HOMELESS_ANXIETY.csv s3://fridayelement-datasets/
              aws s3 cp ./files/SF_HOMELESS_DEMOGRAPHICS.csv s3://fridayelement-datasets/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}



   
